"""Add ai_answers table and posts fulltext index

Revision ID: 8f2c922fc69e
Revises: 5c66a9038431
Create Date: 2026-08-13 16:30:06.767044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f2c922fc69e'
down_revision: Union[str, None] = '5c66a9038431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('retrieval_path', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_ai_answers_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_answers')),
    sa.UniqueConstraint('post_id', name=op.f('uq_ai_answers_post_id'))
    )
    # 为 posts 表添加全文搜索索引（使用 simple 配置兼容中文）
    op.execute("CREATE INDEX IF NOT EXISTS ix_posts_content_fts ON posts USING gin(to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, '')))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_posts_content_fts")
    op.drop_table('ai_answers')
    # ### end Alembic commands ###
